pool:
  name: Hosted VS2017
  demands: npm

steps:
- task: DownloadGitHubRelease@0
  inputs:
    connection: 'GitHub connection 1'
    userRepository: 'losper/passoa'
    defaultVersionType: 'latest'
    itemPattern: 'passoa-msvc*'
    downloadPath: './'
- task: DownloadGitHubRelease@0
  inputs:
    connection: 'GitHub connection 1'
    userRepository: 'pass0a/package'
    defaultVersionType: 'latest'
    itemPattern: '*.7z'
    downloadPath: './'

- script: |
   mkdir depends
   7z x passoa*.zip -r -o./depends/passoa -y
   7z x browser.7z -r -o./depends/browser -y
   7z x db.7z -r -o./depends/db -y
   7z x adb.7z -r -o./depends/adb -y
   cd depends
   curl -L -o vcredist_x86.exe https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x86.exe
   curl -L -o latest_usb_driver_windows.zip https://dl-ssl.google.com/android/repository/latest_usb_driver_windows.zip?hl=zh-CN
   
   ls
  displayName: 'install all depends'

- script: |
   curl -L -o pcan-basic.zip http://www.peak-system.com/fileadmin/media/files/pcan-basic.zip
   7z x pcan-basic.zip -r -o./ -y
  displayName: 'install pcanbase'

- task: Npm@1
  displayName: 'npm install'
  inputs:
    workingDir: service
    verbose: false

- task: Npm@1
  displayName: 'npm install'
  inputs:
    workingDir: views
    verbose: false

- task: Npm@1
  displayName: 'npm custom'
  inputs:
    command: custom
    workingDir: service
    verbose: false
    customCommand: 'run pm'

- task: Npm@1
  displayName: 'npm custom'
  inputs:
    command: custom
    workingDir: service
    verbose: false
    customCommand: 'run build'

- task: Npm@1
  displayName: 'npm custom'
  inputs:
    command: custom
    workingDir: views
    verbose: false
    customCommand: 'run build'

- script: |
   cp service/node_modules/@passoa/ depends/passoa/msvc/node_modules/@passoa/ -rf
  displayName: 'install node_mudules/@passoa'
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))


- task: nsis@1
  inputs:
    scriptFile: 'reveal.nsi'
    justInclude: 'no'
    includeMorePlugins: 'no'
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))

- task: nsis@1
  inputs:
    scriptFile: 'poseidon.nsi'
    justInclude: 'no'
    includeMorePlugins: 'no'
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'RevealSetup.exe'
    includeRootFolder: false
    archiveType: '7z'
    archiveFile: '$(Build.ArtifactStagingDirectory)/Reveal-$(Build.SourceBranchName)-$(Build.BuildId).7z'
    replaceExistingArchive: true
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'PoseidonSetup.exe'
    includeRootFolder: false
    archiveType: '7z'
    archiveFile: '$(Build.ArtifactStagingDirectory)/Poseidon-$(Build.SourceBranchName)-$(Build.BuildId).7z'
    replaceExistingArchive: true
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))

- task: GitHubRelease@0
  inputs:
    gitHubConnection: 'GitHub connection 1'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    target: '$(Build.SourceVersion)'
    tagSource: 'auto'
    releaseNotesFile: 'ChangeLog'
    addChangeLog: false
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))
